let q = 10;
let q1 = "10";
let q3;
let q4 = 100;
let q5 = null;
console.log(q);
console.log(q1);
console.log(q3);
console.log(100 >= 101);
console.log(q5);
let nemeh = 11;
let nemeh1 = 11;
console.log(nemeh + nemeh1);
let fn = "firstname";
console.log(fn);
let ln = "lastname";
console.log(ln);
let status = "marital status";
console.log(status);
country = "country";
age = "age";
console.log(country);
console.log(age);
let text = "firstname lastname country age";
console.log(text);
let a = 4;
let b = 4;
let c = 8;
console.log(a + c + b);
let radius = 2;
const PI = 3.14;
console.log(radius * radius * PI + "CMK");
let y2 = 4;
let y1 = 2;
let x2 = 4;
let x1 = 2;
let m = (y2 - y1) / (x2 - x1);
console.log(m);
let gb = 15;
let mb = gb * 1024;
console.log("15gb iig mbruu hurwuuleh yum bol=" + mb + "MB");
let download = 15;
let time = 3;
let bitrate = download * 8000000;
console.log(bitrate + "bit");
let side1 = 11;
let side2 = 14;
let side3 = 28;
console.log((side1 * side2) / 2 + "cm kvadrat");
let t1 = 50;
const fahrenheit = 1.8;
console.log(t1 * fahrenheit + 32 + "fahrenheit");
let t2 = 122;
let fahrenheit2 = 1.8;
const togtmol = 32;
console.log((t2 - togtmol) / fahrenheit);
let huwisagch1 = 15;
let huwisagch2 = 10;
console.log(huwisagch1 + huwisagch2);
console.log(huwisagch1 - huwisagch2);
console.log(huwisagch1 * huwisagch2);
console.log(huwisagch1 / huwisagch2);
let cm = 20;
const INCH = 2.54;
console.log(cm / INCH + "inch");
let inch = 20;
const cm1 = 2.54;
console.log(inch * cm1 + "cm");
let rad = 4;
const PI1 = 3.14;
console.log(PI1 * rad * rad + "cmk");
let rad1 = 2;
PI3 = 3.14;
console.log(2 * PI3 * rad1 + "m");
let number = 123;
console.log("ehni tsipr " + 1);
let s = "Baby ";
let s1 = "Shark, ";
let s2 = "doo-doo, ";
let s3 = "doo-doo,";
let s4 = "Mommy ";
console.log(s + s1 + s2 + s3);
console.log(s + s1 + s2 + s3);
console.log(s + s1 + s2 + s3);
console.log(s4 + s1 + s2 + s3);
console.log(s4 + s1 + s2 + s3);
