let q = 10;
let q1 = "10";
let q3;
let q4 = 100;
let q5 = null;
console.log(q);
console.log(q1);
console.log(q3);
console.log(100 >= 101);
console.log(q5);
let nemeh = 11;
let nemeh1 = 11;
console.log(nemeh + nemeh1);
let fn = "firstname";
console.log(fn);
let ln = "lastname";
console.log(ln);
let status = "marital status";
console.log(status);
country = "country";
age = "age";
console.log(country);
console.log(age);
let text = "firstname lastname country age";
console.log(text);
let a = 4;
let b = 4;
let c = 8;
console.log(a + c + b);
let radius = 10;
let radius1 = 10;

333;
console.log(radius * radius1);
